import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { format } from 'prettier';
import {
  FaArrowLeft,
  FaArrowRight,
  FaBookOpen,
  FaCheck,
  FaClock,
  FaCopy,
  FaFeatherPointed,
  FaLock,
  FaPenToSquare,
  FaTrashCan,
  FaUnlockKeyhole,
  FaUserGroup,
} from 'react-icons/fa6';

const icons = {
  arrowLeft: FaArrowLeft,
  arrowRight: FaArrowRight,
  bookOpen: FaBookOpen,
  check: FaCheck,
  clock: FaClock,
  copy: FaCopy,
  feather: FaFeatherPointed,
  lock: FaLock,
  edit: FaPenToSquare,
  trash: FaTrashCan,
  unlock: FaUnlockKeyhole,
  users: FaUserGroup,
};

const generated = Object.fromEntries(
  Object.entries(icons).map(([name, component]) => [
    name,
    renderToStaticMarkup(createElement(component, { focusable: false })),
  ]),
);
const source = await format(
  `// Generated by npm run generate:icons. Do not edit manually.\nexport const iconSvg = ${JSON.stringify(generated, null, 2)} as const;\n\nexport type IconName = keyof typeof iconSvg;\n`,
  { parser: 'typescript', singleQuote: true },
);
const here = dirname(fileURLToPath(import.meta.url));
const output = resolve(here, '../src/generated/icons.ts');
await mkdir(dirname(output), { recursive: true });
await writeFile(output, source, 'utf8');
